export const Data = {
  abilities: [
    {
      label: "8 (Hachi)",
      effect: "Reaction Speed",
      value: "+2.5%",
      sources: ["Astray Red Frame Body"],
    },
    {
      label: "Active Binder",
      effect: "Boost Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "AGE System",
      effect: "Awakening Duration",
      value: "+2s",
      sources: [
        "Gundam AGE-1 Body",
        "Gundam AGE-2 Normal Body",
        "Gundam AGE-3 Normal Body",
        "Gundam AGE-FX Body",
        "Gundam AGE-2 Dark Hound Body",
      ],
    },
    {
      label: "Ahab Reactor",
      effect: "Thruster Capacity",
      value: "+5000",
      sources: [],
    },
    {
      label: "Alaya-Vijnana System",
      effect: "Reaction Speed",
      value: "+5%",
      sources: ["Gundam Barbatos"],
    },
    {
      label: "Anti-Beam Coating",
      effect: "Beam Resistance",
      value: "+10%",
      sources: [],
    },
    {
      label: "Apogee Motor",
      effect: "Movement Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Armed Armor XC",
      effect: "Reaction Speed",
      value: "+4.5%",
      sources: [],
    },
    {
      label: "Assault Shroud",
      effect: "Durability",
      value: "+10%",
      sources: ["Duel Gundam Assault Shroud"],
    },
    {
      label: "Astray Special Frame",
      effect: "Reaction Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "Atmospheric Thermonuclear Jet Engine",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Autonomous Dual Column Processing AI",
      effect: "Reaction Speed",
      value: "+2%",
      sources: [],
    },
    {
      label: "Beam Jytte",
      effect: "Beam Guard",
      value: "+8%",
      sources: [],
    },
    {
      label: "Beam resistance coating (Shield)",
      effect: "Beam Guard",
      value: "+8%",
      sources: [],
    },
    {
      label: "Beam resistant coating",
      effect: "Beam Guard",
      value: "+8%",
      sources: [],
    },
    {
      label: "Beam Shield (Anti-Beam)",
      effect: "Beam Guard",
      value: "+10%",
      sources: [],
    },
    {
      label: "Beam Shield (Anti-Physical)",
      effect: "Physical Guard",
      value: "+10%",
      sources: [],
    },
    {
      label: "Bio-sensor",
      effect: "Reaction Speed",
      value: "+5%",
      sources: ["Z Gundam Body", "ZZ Gundam Body"],
    },
    {
      label: "Biocomputer",
      effect: "Reaction Speed",
      value: "+5%",
      sources: ["Crossbone Gundam X1 Body"],
    },
    {
      label: "Bipod",
      effect: "Ranged Weapon Burst Ability",
      value: "+30%",
      sources: ["Ez8 Shield", "GN Sniper Rifle"],
    },
    {
      label: "Blade Antenna",
      effect: "Awakening Duration",
      value: "+1s",
      sources: [],
    },
    {
      label: "Booster Binder",
      effect: "Boost Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "Chobham Armor Construction",
      effect: "Physical Guard",
      value: "+10%",
      sources: [],
    },
    {
      label: "Clavicle Antenna",
      effect: "Durability",
      value: "+5%",
      sources: ["Gundam Exia Body"],
    },
    {
      label: "Colloid particle machine control",
      effect: "Movement Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Combat Support AI",
      effect: "Reaction Speed",
      value: "+2%",
      sources: [],
    },
    {
      label: "DG Cells",
      effect: "Auto-Repair",
      value: "+1000/s",
      sources: ["Master Gundam"],
    },
    {
      label: "DHGCP",
      effect: "Thruster Capacity",
      value: "+5000",
      sources: [],
    },
    {
      label: "Double Pack",
      effect: "Ranged Weapon Gauge Capacity",
      value: "+30%",
      sources: ["TR-1 Advanced Hazel"],
    },
    {
      label: "Drum Frame",
      effect: "Durability",
      value: "+15%",
      sources: [],
    },
    {
      label: "E Carbon (GN particle coating)",
      effect: "Durability",
      value: "+20%",
      sources: ["00 Series"],
    },
    {
      label: "Energy Pack",
      effect: "Ranged Weapon Gauge Capacity",
      value: "+20%",
      sources: ["Full Armor Gundam Backpack"],
    },
    {
      label: "Energy Pod",
      effect: "Option Gauge Capacity",
      value: "+20%",
      sources: ["Gundam X"],
    },
    {
      label: "Energy Supply System",
      effect: "Ranged Weapon Charge Speed",
      value: "+20%",
      sources: ["Lightning Gundam Arms"],
    },
    {
      label: "Epyon Wing",
      effect: "Boost Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Eyepatch-Sight Visor",
      effect: "Shooting Mode Damage",
      value: "+30%",
      sources: ["AGE-2 Dark Hound"],
    },
    {
      label: "Fighting Sight",
      effect: "Enemy Flinching Rate",
      value: "+50%",
      sources: [],
    },
    {
      label: "First-Generation Movable Frame",
      effect: "Durability",
      value: "+5%",
      sources: ["Rick Dias"],
    },
    {
      label: "Flash System",
      effect: "Reaction Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "Flexible Thruster",
      effect: "Boost Speed",
      value: "+7%",
      sources: [],
    },
    {
      label: "Flexible Thruster Binder",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Fluid Pulse Accelerator",
      effect: "Movement Speed",
      value: "+7%",
      sources: [],
    },
    {
      label: "FRP Unit",
      effect: "Movement Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "Full Psycho Frame",
      effect: "Reaction Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Genso-nickel plating",
      effect: "Durability",
      value: "+20%",
      sources: ["Musha Gundam"],
    },
    {
      label: "GN Drive",
      effect: "Trance Duration",
      value: "+10s",
      sources: [],
    },
    {
      label: "Gundam Frame",
      effect: "Durability",
      value: "+15%",
      sources: [],
    },
    {
      label: "Gunport",
      effect: "Ranged Weapon Burst Ability",
      value: "+20%",
      sources: ["Freedom Shield", "Justice Shield"],
    },
    {
      label: "Haro",
      effect: "Reaction Speed",
      value: "+2.5%",
      sources: [],
    },
    {
      label: "Heat Blade",
      effect: "Physical Guard",
      value: "+1%",
      sources: [],
    },
    {
      label: "Heat-Radiating Fin",
      effect: "Trance Duration",
      value: "+5s",
      sources: [],
    },
    {
      label: "High Output Hover Unit",
      effect: "Movement Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "High Output Movable Thruster",
      effect: "Boost Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "High-Mobility Plate",
      effect: "Boost Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "High-Performance Control Computer",
      effect: "Option Charge Speed",
      value: "+15%",
      sources: ["S Gundam", "Ex-S Gundam Body"],
    },
    {
      label: "High-Performance Optical Sensor Unit",
      effect: "Shooting Mode Damage",
      value: "+50%",
      sources: ["TR-1 Advanced Hazel Head"],
    },
    {
      label: "High-Power Generator",
      effect: "Boost Recovery",
      value: "+15%",
      sources: [],
    },
    {
      label: "High-Precision Gun Camera",
      effect: "Shooting Mode Damage",
      value: "+50%",
      sources: ["Cherudim Gundam Head"],
    },
    {
      label: "High-Sensitivity Sensor",
      effect: "Ranged Weapon Tracking Ability",
      value: "+25%",
      sources: ["Gundam Gusion Rebake Head"],
    },
    {
      label: "High-Thrust Booster Unit",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Horns of the Buffalo",
      effect: "Awakening Duration",
      value: "+1.5s",
      sources: [],
    },
    {
      label: "HPHGCP Generator",
      effect: "Thruster Capacity",
      value: "+5000",
      sources: [],
    },
    {
      label: "Hrududu",
      effect: "Thruster Capacity",
      value: "+4000",
      sources: [],
    },
    {
      label: "Hyper Boost",
      effect: "Boost Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "Hyper Deuterion Engine",
      effect: "Option Charge Speed",
      value: "+20%",
      sources: ["Legend Gundam", "Destiny Gundam Body"],
    },
    {
      label: "I Field Beam Drive",
      effect: "Movement Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "IFS Unit",
      effect: "Option Equipment DPS",
      value: "+7500",
      sources: [],
    },
    {
      label: "Indirect Sealing",
      effect: "Parts-Out Resistance",
      value: "+25%",
      sources: ["Full Armor Gundam Head", "Psycho Zaku Legs/Arms"],
    },
    {
      label: "Intention Automatic System",
      effect: "Reaction Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Invisible Titanium",
      effect: "Durability",
      value: "+20%",
      sources: ["G-Self parts"],
    },
    {
      label: "Laminate Armor",
      effect: "Beam Guard",
      value: "+10%",
      sources: [],
    },
    {
      label: "Large Anti-Beam Armor",
      effect: "Beam Guard",
      value: "+8%",
      sources: [],
    },
    {
      label: "Large Propellant Tank",
      effect: "Boost Recovery Speed",
      value: "+20%",
      sources: ["Gundam Barbatos Body"],
    },
    {
      label: "Large Resistance Physical Armor",
      effect: "Physical Guard",
      value: "+8%",
      sources: [],
    },
    {
      label: "Magnet Coating",
      effect: "Reaction Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "Maneuvering Support AI",
      effect: "Reaction Speed",
      value: "+2%",
      sources: [],
    },
    {
      label: "Medium Resistance Physical Armor",
      effect: "Physical Guard",
      value: "+5%",
      sources: [],
    },
    {
      label: "Medium-Sized Anti-Beam Armor",
      effect: "Beam Guard",
      value: "+5%",
      sources: [],
    },
    {
      label: "MFE-type Gundium FGI Composite Armor",
      effect: "Durability",
      value: "+20%",
      sources: ["SUMO Body"],
    },
    {
      label: "Minovsky Drive",
      effect: "Boost Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "Minovsky Flight",
      effect: "Boost Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Movable Booster Pod + Shield Booster",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Movable Frame",
      effect: "Durability",
      value: "+10%",
      sources: [
        "Ex-S Gundam Arms/Legs",
        "S Gundam Arms/Legs",
        "Z Gundam Arms/Legs",
        "ZZ Gundam Arms/Legs",
      ],
    },
    {
      label: "Movable Shield",
      effect: "Boost Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "Multi-purpose Sensor Unit",
      effect: "Increase in EX Gauge when Attack hits",
      value: "+20%",
      sources: ["Aegis Gundam Head"],
    },
    {
      label: "Multiple Construction Armor (MCA)",
      effect: "Durability",
      value: "+15%",
      sources: ["Crossbone Gundam Body"],
    },
    {
      label: "Nanolaminate Armor",
      effect: "Physical Resistance",
      value: "+15%",
      sources: ["Gundam Barbatos Body"],
    },
    {
      label: "Nanoskin",
      effect: "Auto-Repair",
      value: "+2000/s",
      sources: ["Turn A Body/Legs", "Turn X Body/Legs"],
    },
    {
      label: "New Model Generator",
      effect: "Boost Recovery",
      value: "+25%",
      sources: [],
    },
    {
      label: "Nuclear engine",
      effect: "Thruster Capacity",
      value: "+3500",
      sources: [],
    },
    {
      label: "Nuclear Fission Reactor",
      effect: "Thruster Capacity",
      value: "+4000",
      sources: [],
    },
    {
      label: "Pair Beam Coating",
      effect: "Beam Guard",
      value: "+6%",
      sources: [],
    },
    {
      label: "Phase Shift Armor",
      effect: "Physical Resistance",
      value: "+15%",
      sources: [],
    },
    {
      label: "Photon Balancer",
      effect: "Cancel Combo Damage",
      value: "+10%",
      sources: [],
    },
    {
      label: "Photon Battery",
      effect: "Thruster Capacity",
      value: "+5000",
      sources: [],
    },
    {
      label: "Plasma compression reactor",
      effect: "Thruster Capacity",
      value: "+4500",
      sources: [],
    },
    {
      label: "Plavsky Particle Control",
      effect: "Movement Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Power Extender",
      effect: "Option Gauge Capacity",
      value: "+30%",
      sources: ["Strike Noir Gundam"],
    },
    {
      label: "Propellant",
      effect: "Thruster Capacity",
      value: "+2000",
      sources: [],
    },
    {
      label: "Propellant Tank",
      effect: "Thruster Capacity",
      value: "+3000",
      sources: [],
    },
    {
      label: "PS Special Frame",
      effect: "Reaction Speed",
      value: "+4%",
      sources: [],
    },
    {
      label: "Pseudo Solar reactor",
      effect: "Trance Duration",
      value: "+5s",
      sources: [],
    },
    {
      label: "Psycho-frame",
      effect: "Reaction Speed",
      value: "+4.5%",
      sources: [],
    },
    {
      label: "Psycommu",
      effect: "Reaction Speed",
      value: "+4%",
      sources: [],
    },
    {
      label: "Quantum Brainwave Control System",
      effect: "Reaction Speed",
      value: "+4.5%",
      sources: [],
    },
    {
      label: "Quasi-psycommu",
      effect: "Reaction Speed",
      value: "+3.5%",
      sources: [],
    },
    {
      label: "Radiator Plate",
      effect: "Boost Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "Reactive Armor",
      effect: "Physical Resistance",
      value: "+10%",
      sources: [],
    },
    {
      label: "Reuse Psycho Device",
      effect: "Reaction Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Rib Jammer",
      effect: "Camouflage Duration",
      value: "+15s",
      sources: [],
    },
    {
      label: "Rocket Booster",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Rod Antenna",
      effect: "Awakening Duration",
      value: "+1s",
      sources: [],
    },
    {
      label: "Saturn Engine",
      effect: "Boost Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Scanning Turret",
      effect: "Parts-Out Rate",
      value: "+2%",
      sources: ["Mobile SUMO"],
    },
    {
      label: "Self-repairing Micromachinery Technology",
      effect: "Auto-Repair",
      value: "+1500/s",
      sources: ["Stargazer Backpack"],
    },
    {
      label: "Shield Booster",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Spike Armor",
      effect: "Parts-Out Rate",
      value: "+1%",
      sources: [],
    },
    {
      label: "Striking Spike",
      effect: "Parts-Out Rate",
      value: "+1%",
      sources: [],
    },
    {
      label: "Sturm booster",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Sub-generator",
      effect: "Option Charge Speed",
      value: "+20%",
      sources: ["Buster Gundam Leg", "Hyper Impulse Long-Range Sniper Rifle"],
    },
    {
      label: "Subcontrol System",
      effect: "Reaction Speed",
      value: "+1%",
      sources: [],
    },
    {
      label: "Super DRAGOON mobile weapon wing",
      effect: "Boost Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "Super Heavy Armor",
      effect: "Knockback resistance",
      value: "+200%",
      sources: [],
    },
    {
      label: "Super Vernier",
      effect: "Boost Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Tail Binder",
      effect: "Boost Speed",
      value: "+6%",
      sources: [],
    },
    {
      label: "Taurus-Type Movable Thruster",
      effect: "Boost Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Thermonuclear Hover Engine",
      effect: "Movement Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Thruster Vane",
      effect: "Boost Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Trans-Phase armor",
      effect: "Physical Resistance",
      value: "+18%",
      sources: [],
    },
    {
      label: "Twin Drive System",
      effect: "Trance Duration",
      value: "+15s",
      sources: ["00 Raiser Backpack"],
    },
    {
      label: "UE Special Armor",
      effect: "Durability",
      value: "+15%",
      sources: ["Gafran Body"],
    },
    {
      label: "Universal Boost Pod",
      effect: "Boost Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "Variable Phase Shift Armor",
      effect: "Physical Resistance",
      value: "+20%",
      sources: [],
    },
    {
      label: "Vernier Binder",
      effect: "Boost Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "VL Diversion Wing Unit",
      effect: "Boost Speed",
      value: "+10%",
      sources: [],
    },
    {
      label: "VPS Special Frame",
      effect: "Reaction Speed",
      value: "+5%",
      sources: [],
    },
    {
      label: "Wing Binder",
      effect: "Boost Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Wing Binder (Freedom)",
      effect: "Boost Speed",
      value: "+3%",
      sources: [],
    },
    {
      label: "Wing shield",
      effect: "Physical Resistance",
      value: "+10%",
      sources: [],
    },
    {
      label: "Wing Thruster",
      effect: "Boost Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Wing Thruster (Feather Wings)",
      effect: "Boost Speed",
      value: "+8%",
      sources: [],
    },
    {
      label: "Wing Unit",
      effect: "Boost Speed",
      value: "+7%",
      sources: [],
    },
    {
      label: "Yata-no-Kagami",
      effect: "Beam Resistance",
      value: "+20%",
      sources: [],
    },
    {
      label: "Zero Frame",
      effect: "Durability",
      value: "+20%",
      sources: ["Wing Proto Zero", "Wing Zero Custom"],
    },
    {
      label: "ZERO System Copy",
      effect: "Awakening Duration",
      value: "+1.5s",
      sources: [],
    },
  ],
  derives: [
    ["Gundam", "No sources"],
    ["Phenex", "No sources"],
    ["Gundam Barbatos Lupus", "No sources"],
    ["Gundam Kimaris", "No sources"],
    ["Arche Gundam", "No sources"],
    ["Gundam AGE-FX", "No sources"],
    ["[HD] G-3 Gundam", "Gundam"],
    ["GM Command", "Gundam"],
    ["GM II", "Gundam"],
    ["[HD] Guntank", "Gundam"],
    ["Gundam F91", "Gundam"],
    ["[all but HD] Perfect Gundam", "Gundam"],
    ["Gundam Exia", "Gundam"],
    ["Guncannon", "Gundam"],
    ["Gundam Ground Type", "Gundam"],
    ["[HD] Full Armor Gundam", "Gundam"],
    ["Gundam G-Self", "Gundam"],
    ["Gundam AGE-1 Normal/Titus", "Gundam"],
    ["Shin Musha Gundam", "Gundam"],
    ["Victory Gundam", "Gundam"],
    ["G-3 Gundam", "GM"],
    ["[all but BP] Blue Destiny Unit 1", "GM"],
    ["Gundam F91", "GM"],
    ["[all but HD] Perfect Gundam", "GM"],
    ["GM II", "GM"],
    ["Gundam G-Self", "GM"],
    ["Gundam AGE-1 Normal/Titus", "GM"],
    ["Shin Musha Gundam", "GM"],
    ["Victory Gundam", "GM"],
    ["[HD] Char's Gelgoog", "Zaku II"],
    ["Dom Tropen (Sand Brown)", "Zaku II"],
    ["Zaku Minelayer", "Zaku II"],
    ["Zaku II FS", "Zaku II"],
    ["[LG] Zaku II (triple missile pod)", "Zaku II"],
    ["Zudah", "Zaku II"],
    ["[HD] Johnny Ridden's Gelgoog", "Zaku II"],
    ["[HD] Acguy", "Zaku II"],
    ["[all but BD] Johnny Ridden's Zaku II", "Zaku II"],
    ["[all but HD] Shin Matsunaga's Zaku II", "Zaku II"],
    ["[HD] SUMO", "Zaku II"],
    ["Build Burning Gundam", "Zaku II"],
    ["[HD] Gelgoog", "Gouf"],
    ["Dom Tropen", "Gouf"],
    ["[BD/AM/LG] Shin Matsunaga's Zaku II", "Gouf"],
    ["Gouf Custom", "Gouf"],
    ["Zaku II FS", "Gouf"],
    ["Zaku II S", "Gouf"],
    ["Dreissen", "Gouf"],
    ["Dom", "Gouf"],
    ["Den'an Zon", "Gouf"],
    ["Kampfer", "Gouf"],
    ["Hy-Gogg", "Z'Gok"],
    ["[BP] Gelgoog Cannon", "Z'Gok"],
    ["Char's Gelgoog", "Z'Gok"],
    ["Johnny Ridden's Gelgoog", "Z'Gok"],
    ["SUMO", "Z'Gok"],
    ["[all but HD/BP] Kapool", "Z'Gok"],
    ["The-O", "Palace Athene"],
    ["Qubeley Mk-II", "Palace Athene"],
    ["Rozen Zulu", "Palace Athene"],
    ["Shining Gundam", "Rising Gundam"],
    ["Burning Gundam", "Rising Gundam"],
    ["[all but BP] Nobel Gundam", "Rising Gundam"],
    ["Dragon Gundam", "Rising Gundam"],
    ["Shenlong Gundam (EW)", "Wing Gundam (TV)"],
    ["Wing Gundam Proto Zero", "Wing Gundam (TV)"],
    ["Wing Gundam (EW)", "Wing Gundam (TV)"],
    ["Shenlong Gundam (EW)", "Shenlong Gundam (TV)"],
    [("[all but BP] Nobel Gundam", "Shenlong Gundam (TV)")],
    ["Tallgeese III", "Tallgeese"],
    ["Wing Gundam (EW)", "Tallgeese"],
    ["Serpent Custom", "Tallgeese"],
    ["Gundam Deathscythe Hell", "Tallgeese"],
    ["Gundam Sandrock (EW)", "Tallgeese"],
    ["Gundam Heavyarms", "Tallgeese"],
    ["Wing Gundam Zero (EW)", "Tallgeese"],
    ["[HD] Tallgeese II", "Tallgeese"],
    ["Crossbone Gundam X1", "Gundam X"],
    ["Gundam Virsago", "Gundam X"],
    ["[BP] Gundam X Divider", "Gundam X"],
    ["[BD/LG] Crossbone Gundam X1 Kai Kai", "Gundam X"],
    ["Impulse Gundam", "Strike Gundam"],
    ["[BP] Force Impulse Gundam", "[BP] Aile Strike Gundam"],
    ["[all but HD] Duel Gundam Assault Shroud", "Strike Gundam"],
    ["Stargazer", "Strike Gundam"],
    ["Strike Noir", "Strike Gundam"],
    ["[BP] Strike Rouge (Ootori)", "[BP] Aile Strike Gundam"],
    ["Freedom Gundam", "Strike Gundam"],
    ["[BP] Launcher Strike Gundam", "[BP] Aile Strike Gundam"],
    ["Strike Rouge", "Strike Gundam"],
    ["[BP] Strike Rouge IWSP", "[BP] Aile Strike Gundam"],
    ["Build Strike Gundam", "Strike Gundam"],
    ["[BP] Sword Strike Gundam", "[BP] Aile Strike Gundam"],
    ["[all but HD] Duel Gundam Assault Shroud", "Duel Gundam"],
    ["Providence Gundam", "Duel Gundam"],
    ["Providence Gundam", "Blitz Gundam"],
    ["[BP]Perfect Strike Gundam", "Blitz Gundam"],
    ["Astray Blue Frame", "Astray Red Frame"],
    ["Astray Green Frame", "Astray Red Frame"],
    ["[HD] Astray Red Dragon", "Astray Red Frame"],
    ["Astray Blue Frame Second Revise", "Astray Red Frame"],
    ["Astray Gold Frame Amatsu", "Astray Red Frame"],
    ["[BP] Astray Red Frame (Flight Unit)", "Astray Red Frame"],
    ["[LG/BP] Astray Red Frame Kai", "Astray Red Frame"],
    ["Palace Athene", "Astray Red Frame"],
    ["Strike Noir", "Gundam Exia"],
    ["Gundam Dynames", "Gundam Exia"],
    ["Gundam Virtue", "Gundam Exia"],
    ["Astray Blue Frame", "Gundam Exia"],
    ["GN-X", "Gundam Exia"],
    ["00 Qan[T]", "Gundam Exia"],
    ["Impulse Gundam", "Gundam Exia"],
    ["[BP] Force Impulse Gundam", "Gundam Exia"],
    ["Freedom Gundam", "Gundam Exia"],
    ["GN Archer", "Gundam Exia"],
    ["Strike Rouge", "Gundam Exia"],
    ["[BP] Strike Rouge IWSP", "Gundam Exia"],
    ["Gundam Kyrios", "Gundam Exia"],
    ["Build Strike Gundam", "Gundam Exia"],
    ["[BP] Sword Strike Gundam", "Gundam Exia"],
    ["Unicorn Gundam", "Phenex"],
    ["Banshee", "Phenex"],
    ["[AM] Banshee (Armed Armor)", "Phenex"],
    ["Zeta Gundam", "Scramble Gundam"],
    ["Destiny Gundam", "Scramble Gundam"],
    ["Build Burning Gundam", "Scramble Gundam"],
    ["Gundam Barbatos", "Gundam Barbatos 6th Form"],
    ["Sinanju", "Rebawoo"],
    ["Gundam Barbatos", "Gundam Gusion"],
    ["Gundam Astaroth", "Gundam Gusion"],
    ["Gundam AGE-2 Normal", "Gundam AGE-FX"],
    ["Gundam AGE-3 Fortress", "Gundam AGE-FX"],
    ["Gundam AGE-1 Normal/Titus", "Gundam AGE-FX"],
    ["[BP] Gundam Kimaris (Booster)", "Gundam Kimaris"],
    ["Gundam Barbatos", "Gundam Kimaris"],
    ["Gouf", "Mobile Worker"],
    ["Susanowo", "Arche Gundam"],
    ["Gundam Barbatos", "Gundam Gusion Rebake"],
    ["[HD] Gundam Gusion Rebake (Aiming Mode Head)", "Gundam Gusion Rebake"],
    ["[all but BP] Strike Gundam", "Aegis Gundam"],
    ["[BP] Aile Strike Gundam", "Aegis Gundam"],
    ["Blitz Gundam", "Aegis Gundam"],
    ["Duel Gundam", "Aegis Gundam"],
    ["Gundam Barbatos", "Gundam Barbatos Lupus"],
    ["Gundam Gusion Rebake", "Gundam Barbatos Lupus"],
    ["[HD] Gundam Gusion Rebake (Aiming Mode Head)", "Gundam Barbatos Lupus"],
    ["Gundam Barbatos", "[AM] Gundam Barbatos Lupus (200mm Arm Cannon)"],
    ["Gundam Gusion Rebake", "[AM] Gundam Barbatos Lupus (200mm Arm Cannon)"],
    ["Strike Gundam", "Buster Gundam"],
    ["[BP] Aile Strike Gundam", "Buster Gundam"],
    ["Blitz Gundam", "Buster Gundam"],
    ["Duel Gundam", "Buster Gundam"],
    ["Gundam AGE-1 Titus", "[BD/AM/LG] Gundam AGE-1 Normal"],
    ["Gundam AGE-2 Normal", "[BD/AM/LG] Gundam AGE-1 Normal"],
    ["[BD/AM/LG] Gundam AGE-3 Normal", "[BD/AM/LG] Gundam AGE-1 Normal"],
    ["Burning Gundam", "Gundam Rose"],
    ["[HD] Ball (Cannon)", "[HD/BD/LG] Ball"],
    ["[HD/BD/LG] Ball", "[HD/BD/LG] Ball"],
    ["Gundam G-Self", "Kabakali"],
    ["Banshee", "Kabakali"],
    ["[LG] Kabakali (Shield)", "Kabakali"],
    ["Build Strike Gundam", "Beginning 30 Gundam"],
    ["Unicorn Gundam", "Full Armor Unicorn Gundam"],
    ["Gundam TR-6 [Woundwort]", "Gundam TR-1 [Advanced Hazel]"],
    ["Gundam TR-6 [Woundwort]", "[HD] High-Performance Optical Sensor Unit"],
    ["Gundam NT-1", "GM Command"],
    ["[all but BP] Blue Destiny Unit 1", "GM Command"],
    ["Pale Rider", "GM Command"],
    ["TR-1 [Advanced Hazel]", "GM Command"],
    ["Crossbone Gundam X1", "Gundam F91"],
    ["Gundam Virsago", "Gundam F91"],
    ["Strike Gundam", "Gundam F91"],
    ["[BP] Aile Strike Gundam", "Gundam F91"],
    ["Duel Gundam", "Gundam F91"],
    ["[BP] Gundam X Divider", "Gundam F91"],
    ["Full Armor Gundam", "[all but HD] Perfect Gundam"],
    ["Blue Destiny Unit 2", "Gundam Ground Type"],
    ["Gundam GP02A", "Gundam Ground Type"],
    ["Astray Red Frame", "Gundam Ground Type"],
    ["GN-X", "Gundam G-Self"],
    ["Gundam Barbatos", "Gundam G-Self"],
    ["Gundam Kyrios", "Gundam G-Self"],
    ["[HD] Victory Gundam Hexa", "Victory Gundam"],
    ["[BP] V-Dash Gundam", "Victory Gundam"],
    ["[LG/BP] V2 Buster Gundam", "Victory Gundam"],
    ["V2 Gundam", "Victory Gundam"],
    ["Gundam GP03S", "Victory Gundam"],
    ["Gerbera Tetra", "Victory Gundam"],
    ["Zeta Gundam", "Victory Gundam"],
    ["Turn-A Gundam", "Victory Gundam"],
    ["Gundam X", "Victory Gundam"],
    ["Blitz Gundam", "Victory Gundam"],
    ["Gundam NT-1", "G-3 Gundam"],
    ["Gundam GP01", "G-3 Gundam"],
    ["Gundam Exia", "G-3 Gundam"],
    ["Guncannon", "G-3 Gundam"],
    ["Guntank", "G-3 Gundam"],
    ["Rising Gundam", "G-3 Gundam"],
    ["Gundam Ground Type", "G-3 Gundam"],
    ["Rick Dias", "G-3 Gundam"],
    ["Pale Rider", "[all but BP] Blue Destiny Unit 1"],
    ["Blue Destiny Unit 3", "[all but BP] Blue Destiny Unit 1"],
    ["TR-1 [Advanced Hazel]", "[all but BP] Blue Destiny Unit 1"],
    ["GM Custom", "GM II"],
    ["GM III", "GM II"],
    ["Powered GM Cardigan", "GM II"],
    ["[HD] Zudah (Commander Type)", "Zudah"],
    ["Tallgeese III", "Zudah"],
    ["Serpent Custom", "Zudah"],
    ["Dom", "Zudah"],
    ["Gundam Sandrock (EW)", "Zudah"],
    ["Wing Gundam (TV)", "Zudah"],
    ["Geara Doga", "[all but HD] Shin Matsunaga's Zaku II"],
    ["Turn-X", "[HD] SUMO"],
    ["[HD/LG] Fuunsaiki", "Build Burning Gundam"],
    ["Kampfer", "Gouf Custom"],
    ["Tallgeese", "Gouf Custom"],
    ["Hy-Gogg", "Zaku II S"],
    ["Zaku Minelayer", "Zaku II S"],
    ["[LG] Zaku II", "Zaku II S"],
    ["Zudah", "Zaku II S"],
    ["[all but HD] Char's Gelgoog", "Zaku II S"],
    ["Zaku II FZ", "Zaku II S"],
    ["[all but LG] Acguy", "Zaku II S"],
    ["Qubeley", "Zaku II S"],
    ["Gelgoog J", "Zaku II S"],
    ["[all but HD/BP] Kapool", "Zaku II S"],
    ["Rezin's Geara Doga", "Dreissen"],
    ["The-O", "Dreissen"],
    ["Gouf Custom", "Dom"],
    ["Gyan", "Dom"],
    ["Dom Tropen (Sand Brown)", "Dom"],
    ["Dreissen", "Dom"],
    ["Dom Tropen", "Dom"],
    ["Den'an Zon", "Dom"],
    ["Build Burning Gundam", "Dom"],
    ["[all but BP] Zeong", "Char's Gelgoog"],
    ["[AM] Perfect Zeong", "Char's Gelgoog"],
    ["[BP] Gelgoog Cannon", "Char's Gelgoog"],
    ["Johnny Ridden's Gelgoog", "Char's Gelgoog"],
    ["[all but AM] Qubeley", "Char's Gelgoog"],
    ["Gelgoog J", "Char's Gelgoog"],
    ["Turn-X", "SUMO"],
    ["SUMO", "[all but HD/BP] Kapool"],
    ["Juaggu", "[all but HD/BP] Kapool"],
    ["Rozen Zulu", "The-O"],
    ["Kshatriya", "Qubeley Mk-II"],
    ["Burning Gundam", "Shining Gundam"],
    ["Master Gundam", "Shining Gundam"],
    ["Shenlong Gundam (TV)", "Burning Gundam"],
    ["Shining Gundam", "[all but BP] Nobel Gundam"],
    ["Master Gundam", "Dragon Gundam"],
    ["Altron Gundam", "Shenlong Gundam (EW)"],
    ["Wing Gundam Proto Zero", "Wing Gundam (EW)"],
    ["Gundam Sandrock Custom", "Wing Gundam (EW)"],
    ["Gundam Deathscythe Hell", "Tallgeese III"],
    ["Gundam Heavyarms", "Tallgeese III"],
    ["Gundam Sandrock Custom", "Gundam Sandrock (EW)"],
    ["[BD/LG] Crossbone Gundam X1 Kai Kai", "Crossbone Gundam X1"],
    ["Gundam Virsago Chest Break", "Gundam Virsago"],
    ["Destiny Gundam", "Impulse Gundam"],
    ["[BP] Sword Impulse Gundam", "[BP] Force Impulse Gundam"],
    ["[BP] Blast Impulse Gundam", "[BP] Force Impulse Gundam"],
    ["Akatsuki", "Freedom Gundam"],
    ["[BP] Oowashi Akatsuki", "Freedom Gundam"],
    ["Infinite Justice Gundam", "Freedom Gundam"],
    ["Strike Freedom Gundam", "Freedom Gundam"],
    ["[BP] Shiranui Akatsuki", "Strike Rouge"],
    ["Akatsuki", "Strike Rouge"],
    ["[BP] Oowashi Akatsuki", "Strike Rouge"],
    ["Stargazer", "Strike Rouge"],
    ["Justice Gundam", "Strike Rouge"],
    ["[BP] Launcher Strike Gundam", "Strike Rouge"],
  ],
  abilityPlacement: [
    {
      ability: "(Body Part Class) EX Enhance",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "(Long Range Weapon Class) EX Enhance",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "(Short Range Weapon Class) EX Enhance",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: false,
    },
    {
      ability: "Aerial Melee Damage",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: false,
    },
    {
      ability: "Attack Hit: Burst Gain",
      head: false,
      body: true,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Increase in EX Gauge when Attack hits",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Attack Hit: Repair",
      head: true,
      body: true,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Auto-Repair per second",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Avoid Instant Death",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Awakening Duration",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Beam Guard",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Beam Resistance",
      head: false,
      body: true,
      arms: false,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Boost Recovery Speed",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Boost",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Camouflage EX Extend",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Close Range Weapon DPS",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: false,
    },
    {
      ability: "Close Range Weapon Mastery",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Combo Cancel Damage",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Damage to Shield",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: false,
    },
    {
      ability: "Defense vs. locked-on enemy",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Durability Recovery",
      head: false,
      body: true,
      arms: false,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Durability",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Enemy Kill: Burst Charge",
      head: false,
      body: true,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Enemy Kill: EX Charge",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Enemy Kill: Option Charge",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: true,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Enemy Kill: Repair",
      head: false,
      body: true,
      arms: false,
      legs: true,
      backpack: true,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Enemy Targeting Likelihood Down",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Enemy Targeting Likelihood Up",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "EX Cancel Damage",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "EX Enemy Kill: EX Charge",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Induce Knockback",
      head: false,
      body: false,
      arms: false,
      legs: true,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Induce Stagger",
      head: false,
      body: true,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Inflict Parts Out",
      head: true,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Knockback Resistance",
      head: false,
      body: true,
      arms: false,
      legs: true,
      backpack: true,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Long Range Weapon DPS",
      head: true,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Long Range Weapon Mastery",
      head: true,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Mobility",
      head: false,
      body: false,
      arms: false,
      legs: true,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Near Death Damage Inflict",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Near Death Damage Reduction",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Near Death Stagger/Knockback Immunity",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Option Charge Speed",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Option DPS",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Option Gauge Capacity",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Parts Break: Burst Charge",
      head: false,
      body: true,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Parts Break: EX Charge",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Parts Break: Option Charge",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: true,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Parts Break: Repair",
      head: false,
      body: true,
      arms: false,
      legs: true,
      backpack: true,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Parts-Out Resistance",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Physical Guard",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Physical Resistance",
      head: false,
      body: true,
      arms: false,
      legs: true,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Ranged Weapon Blast Damage",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Blast Radius",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Bullet Speed",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Burst Ability",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Charge Speed",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Gauge Capacity",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Penetration",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Proximity Fuse",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Tracking Ability",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Ranged Weapon Velocity",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: true,
    },
    {
      ability: "Response",
      head: true,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Shield Weapon Capacity",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Shield Weapon Charge Speed",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Shield Weapon DPS",
      head: false,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Stagger Resistance",
      head: false,
      body: true,
      arms: false,
      legs: true,
      backpack: true,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Step Distance",
      head: false,
      body: false,
      arms: false,
      legs: true,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Step Invincibility Time",
      head: false,
      body: false,
      arms: false,
      legs: true,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Support EX Extend",
      head: true,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Takedown Kill: EX Charge",
      head: false,
      body: false,
      arms: true,
      legs: false,
      backpack: false,
      shield: false,
      melee: true,
      ranged: true,
    },
    {
      ability: "Thruster Capacity",
      head: false,
      body: true,
      arms: false,
      legs: false,
      backpack: true,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Trance EX Extend",
      head: false,
      body: true,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Treasure Hunter",
      head: true,
      body: false,
      arms: false,
      legs: false,
      backpack: false,
      shield: false,
      melee: false,
      ranged: false,
    },
    {
      ability: "Undetectable by Mines",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: true,
      melee: false,
      ranged: false,
    },
    {
      ability: "Undetectable by Turrets",
      head: true,
      body: true,
      arms: true,
      legs: true,
      backpack: true,
      shield: true,
      melee: false,
      ranged: false,
    },
  ],
}
